- training_id: 1
  body_parts: [2, 5, 6] # スクワット: 太もも、臀部、腰部

- training_id: 2
  body_parts: [4, 6, 5] # デッドリフト: 背中、脚、腰

- training_id: 3
  body_parts: [3, 2, 1] # ベンチプレス: 胸、腕、肩

- training_id: 4
  body_parts: [4, 2] # プルアップ: 背中、二頭筋

- training_id: 5
  body_parts: [6, 5] # レッグプレス: 脚、臀部

- training_id: 6
  body_parts: [1, 2] # ショルダープレス: 肩、三頭筋

- training_id: 7
  body_parts: [2] # バーベルカール: 二頭筋

- training_id: 8
  body_parts: [2] # トライセップスエクステンション: 三頭筋

- training_id: 9
  body_parts: [6] # レッグカール: 太ももの裏

- training_id: 10
  body_parts: [6] # クランチ: 腹筋

- training_id: 11
  body_parts: [6] # プランク: コア

- training_id: 12
  body_parts: [6] # カーフレイズ: ふくらはぎ

- training_id: 13
  body_parts: [4] # ラットプルダウン: 広背筋

- training_id: 14
  body_parts: [3] # ダンベルフライ: 胸

- training_id: 15
  body_parts: [6, 5] # ルーマニアンデッドリフト: ハムストリングス、臀部

- training_id: 16
  body_parts: [6] # レッグエクステンション: 大腿四頭筋