  # スクワット: 太もも
- training_id: 1
  body_part: 2
  # スクワット: 臀部
- training_id: 1
  body_part: 5
  # スクワット: 腰部
- training_id: 1
  body_part: 6

  # デッドリフト: 背中
- training_id: 2
  body_part: 4
  # デッドリフト: 脚
- training_id: 2
  body_part: 6
  # デッドリフト: 腰
- training_id: 2
  body_part: 5

  # ベンチプレス: 胸
- training_id: 3
  body_part: 3
  # ベンチプレス: 腕
- training_id: 3
  body_part: 2
  # ベンチプレス: 肩
- training_id: 3
  body_part: 1

  # プルアップ: 背中
- training_id: 4
  body_part: 4
  # プルアップ: 二頭筋
- training_id: 4
  body_part: 2

  # レッグプレス: 脚
- training_id: 5
  body_part: 6
  # レッグプレス: 臀部
- training_id: 5
  body_part: 5

  # ショルダープレス: 肩
- training_id: 6
  body_part: 1
  # ショルダープレス: 三頭筋
- training_id: 6
  body_part: 2

  # バーベルカール: 二頭筋
- training_id: 7
  body_part: 2

  # トライセップスエクステンション: 三頭筋
- training_id: 8
  body_part: 2

  # レッグカール: 太ももの裏
- training_id: 9
  body_part: 6

  # クランチ: 腹筋
- training_id: 10
  body_part: 6

  # プランク: コア
- training_id: 11
  body_part: 6

  # カーフレイズ: ふくらはぎ
- training_id: 12
  body_part: 6

  # ラットプルダウン: 広背筋
- training_id: 13
  body_part: 4

  # ダンベルフライ: 胸
- training_id: 14
  body_part: 3

  # ルーマニアンデッドリフト: ハムストリングス
- training_id: 15
  body_part: 6
  # ルーマニアンデッドリフト: 臀部
- training_id: 15
  body_part: 5

  # レッグエクステンション: 大腿四頭筋
- training_id: 16
  body_part: 6
