---
- name: "スクワット"
  explanation: "全身の筋力を向上させる基本的なトレーニング。太もも、臀部、腰部の強化に効果的。"

- name: "デッドリフト"
  explanation: "背中、脚、腰の筋肉を鍛えるトレーニング。全身の筋力を高めるのに適している。"

- name: "ベンチプレス"
  explanation: "胸の筋肉、三頭筋、前肩を強化するトレーニング。上半身の筋力を向上させる。"

- name: "プルアップ"
  explanation: "背中の筋肉と二頭筋を鍛える。自重を利用した効果的な上半身トレーニング。"
 
- name: "レッグプレス"
  explanation: "主に脚の筋肉を鍛えるトレーニング。太ももと臀部の強化に有効。"

- name: "ショルダープレス"
  explanation: "肩の筋肉を中心に鍛えるトレーニング。上腕三頭筋にも効果的。"

- name: "バーベルカール"
  explanation: "二頭筋を鍛えるクラシックなトレーニング。腕の強化に適している。"

- name: "トライセップスエクステンション"
  explanation: "上腕三頭筋を集中的に鍛えるトレーニング。腕の裏側を強化する。"

- name: "レッグカール"
  explanation: "ハムストリングス（太ももの裏側の筋肉）を強化するトレーニング。"

- name: "クランチ"
  explanation: "腹筋を鍛える基本的なトレーニング。コアの強化に役立つ。"

- name: "プランク"
  explanation: "コアの筋肉を鍛える静的なトレーニング。体幹の安定性を高める。"

- name: "カーフレイズ"
  explanation: "ふくらはぎの筋肉を鍛えるトレーニング。下腿の強化に効果的。"

- name: "ラットプルダウン"
  explanation: "広背筋を中心に鍛えるトレーニング。背中の筋肉を強化する。"

- name: "ダンベルフライ"
  explanation: "胸の筋肉を鍛え、肩の可動域を広げるトレーニング。"

- name: "ルーマニアンデッドリフト"
  explanation: "ハムストリングスと臀部の筋肉に焦点を当てたデッドリフトのバリエーション。"

- name: "レッグエクステンション"
  explanation: "太ももの前側の筋肉、特に大腿四頭筋を鍛えるトレーニング。"